# Generated by Django 2.2.4 on 2019-10-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qipashuo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u', models.CharField(max_length=64)),
                ('s', models.CharField(max_length=64)),
                ('e', models.CharField(max_length=64)),
            ],
        ),
    ]
