# Generated by Django 2.2.4 on 2019-10-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qipashuo', '0003_auto_20191007_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
