# Generated by Django 2.2.4 on 2019-10-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qipashuo', '0004_user_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='avg',
            field=models.IntegerField(default=0),
        ),
    ]
