# Generated by Django 2.2.4 on 2019-10-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qipashuo', '0005_speaker_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='avg',
            field=models.FloatField(default=0),
        ),
    ]
