# Generated by Django 2.2.4 on 2019-10-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qipashuo', '0006_auto_20191008_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='round',
            name='round_id',
            field=models.IntegerField(default=0),
        ),
    ]
