# Generated by Django 2.2.4 on 2019-10-30 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qipashuo', '0007_auto_20191011_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalSpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GrandFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gov_vote', models.IntegerField(default=0)),
                ('opp_vote', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FinalVoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now=True)),
                ('voted_team', models.CharField(max_length=20)),
                ('best_speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qipashuo.FinalSpeaker')),
            ],
        ),
    ]
