# Generated by Django 2.2.4 on 2019-10-30 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qipashuo', '0009_auto_20191030_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalspeaker',
            old_name='speaker_name',
            new_name='name',
        ),
    ]
