# Generated by Django 2.2.4 on 2019-11-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qipashuo', '0010_auto_20191030_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandfinal',
            name='name',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
