# Generated by Django 2.2.4 on 2019-11-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qipashuo', '0011_grandfinal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalvoter',
            name='best_speaker',
        ),
        migrations.RemoveField(
            model_name='finalvoter',
            name='voted_team',
        ),
    ]
