# Generated by Django 2.2.4 on 2019-11-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qipashuo', '0012_auto_20191101_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalvoter',
            name='type',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
